### ISSUE TITLE
Missing cellranger file

### ISSUE THREAD

**Issue by longfeili5170** [welch-lab/MultiVelo#1]
Thank you for developing such a great package.
I have 10x multiome productive data. But due to some special reasons, I have to use the peak matrix generated by macs2. So I don't have corresponding peak_annotation.tsv and feature_linkage.bedpe files. Are there other ways to generate the corresponding files?
Thanks!

**Comment by danielee0707** [comment]
Hi! Thank you for using the package. For peak annotations, one way to annotate the macs2 called peaks (in bed format) is to use homer's [annotatePeaks](http://homer.ucsd.edu/homer/ngs/annotation.html.) function. Then you'll need to extract the output into a similar format to the 10X annotation file. The CellRanger ARC 2.0.0 format is probably easier to generate, and the description of the 6 columns can be found [here](https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/output/peak-annotations.).

The feature linkage file is for aggregating potential enhancer peaks. There are some ways to find them, for example, using coaccessibility based methods such as [Cicero](https://cole-trapnell-lab.github.io/cicero-release/). Then similarly you'll need to make the format consistent with 10X as described [here](https://support.10xgenomics.com/single-cell-multiome-atac-gex/software/pipelines/latest/output/analysis#fl_output). However, I'll suggest first trying only using promoters and ignoring the enhancer part for now by giving the function an empty bedpe file.

**Comment by longfeili5170** [comment]
I generated peak annotations file through homer. Then I run mv.aggregate_peaks_10x. But it caused the data to become empty.
<img width="616" alt="屏幕快照 2021-12-24 下午9 30 22" src="https://user-images.githubusercontent.com/68364890/147356210-e0541a0d-8846-4bdb-bc61-362edb7fdc95.png">
What could cause this?
Thanks!

**Comment by danielee0707** [comment]
Was the aggregate_peaks_10x able to finish running? If so, I suspect that it didn't find the promoter peaks in the original anndata object. Can you check if the variable names of the original peak-wise atac object (`atac.var_names`) follows `chromosome:start-end` format? 

Also, you can return the promoter gene-peak dictionary with `return_dict=True` argument. Then you can choose a gene and see if its associated peaks do appear in the original atac object. But make sure that it doesn't overwrite the original one with `_, promoter_dict, enhancer_dict = mv.aggregate_peaks_10x...`

**Comment by longfeili5170** [comment]
The default result of macs2 is chromosome-start-end.
Thanks!!!

**Comment by jhong26** [comment]
Hello,
I am analyzing 10x multiome data and looking to aggregate macs2 called peaks so I cannot use the 10x-generated feature_linkage.bedpe file to aggregate peaks. As mentioned earlier, I plan to use cicero to link peaks to other peaks. However, the 10x feature linkage file also identifies peak-gene links combining with gene expression data from scRNAseq. I wonder if I should combine peak-peak links from cicero with gene-peak links from Signac (LinkPeaks) or Archr (addPeak2GeneLinks) to feed into the MultiVelo's aggregate peaks function. Or should I just use the peak-peak links from cicero?
Thank you,
Jason
