### ISSUE TITLE
Questions about error "arange: cannot compute length"

### ISSUE THREAD

**Issue by WangRong423** [welch-lab/MultiVelo#12]
Hi, I ran into a problems using _mv.recover_dynamics_chrom_ , but there was no problem when I combined another 30 samples. 
It happened in the code block below :

```
File "/usr/local/lib/python3.8/dist-packages/multivelo/dynamical_chrom_func.py", line 1180, in initialize_steady_state_params
    for t_sw_1 in np.arange(1, rna_interval-1, 2, dtype=np.float64):
ValueError: arange: cannot compute length
```
Thanks in advance for any help you are able to provide

**Comment by WangRong423** [comment]
There is an unrelated problem. How to extract M1 M2 pattern genes? Thanks

**Comment by danielee0707** [comment]
What is the version of MultiVelo that you're using? May be related to issue #5. Can you update to the latest version 0.1.2 and try again? 

Gene patterns are saved in the `fit_model` column in `adata_result.var` inside the final adata_result object.
You can subset the object with `adata_result[:,adata_result.var['fit_model']==1]` for M1, for example.

**Comment by WangRong423** [comment]
Thank you for your answer ! The problem has been solved, is my own merge object error.
