### ISSUE TITLE
ModuleNotFoundError: No module named 'importlib.metadata'

### ISSUE THREAD

**Issue by AnaAzambuja** [welch-lab/MultiVelo#18]
Hi, 
When importing Multivelo Im getting this error:
ModuleNotFoundError: No module named 'importlib.metadata'

I've checked, and the lirabry is installed. Any ideas?

Thks,
Ana

**Comment by danielee0707** [comment]
Hi. Did you install MultiVelo through pip or conda/mamba environment? And can you try reinstalling importlib_metadata with `pip3 install importlib-metadata`?

**Comment by AnaAzambuja** [comment]
Yep... I installed through pip and tried reinstalling importlib-metadata. 
My Python is 3.7, do you think this has anything to do with this?
Thnks

**Comment by danielee0707** [comment]
Hmm I don't think that's the cause. Can you check the version of importlib-metadata and scVelo? MultiVelo doesn't use this package directly, so it's probably related to scVelo installation. Were you able to install scVelo?

**Comment by AnaAzambuja** [comment]
yep. scVelo is importing (v.  0.2.5)
importlib_metadata v. 1.6.0

**Comment by AnaAzambuja** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/51752362/218280693-a5f62b21-a55e-44d9-84aa-d8dae7804726.png">

**Comment by danielee0707** [comment]
I see. Yeah ok multivelo does use it for version check, whereas scvelo uses setuptools_scm as default.
I just created a python 3.7 environment to test, and I also got this error. However, a new environment with python 3.8 doesn't have this error.
I haven't found a solution to this yet. For now, it may be easier to switch to an environment with python 3.8 in order to resolve this issue.

**Comment by AnaAzambuja** [comment]
I will try that! Thks

**Comment by AnaAzambuja** [comment]
Hi! I am back... So i created the py38 env and now I am finding a new error:
AttributeError: module 'cffi' has no attribute 'FFI'

**Comment by AnaAzambuja** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[4], line 1
----> 1 import multivelo as mv

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/multivelo/__init__.py:1
----> 1 from .auxiliary import (
      2     aggregate_peaks_10x,
      3     tfidf_norm,
      4     knn_smooth_chrom,
      5     calculate_qc_metrics,
      6     ellipse_fit,
      7     compute_quantile_scores,
      8     cluster_by_quantile
      9 )
     11 from .dynamical_chrom_func import (
     12     ChromatinDynamical,
     13     recover_dynamics_chrom,
   (...)
     23     scatter_plot
     24 )
     26 from .steady_chrom_func import (
     27     ChromatinVelocity,
     28     velocity_chrom
     29 )

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/multivelo/auxiliary.py:4
      2 import matplotlib.pyplot as plt
      3 from scipy.sparse import coo_matrix, csr_matrix, diags
----> 4 from umap.umap_ import fuzzy_simplicial_set
      5 from anndata import AnnData
      6 import scanpy as sc

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/umap/__init__.py:2
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      4 try:
      5     with catch_warnings():

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/umap/umap_.py:32
     28 import numba
     30 import umap.distances as dist
---> 32 import umap.sparse as sparse
     34 from umap.utils import (
     35     submatrix,
     36     ts,
     37     csr_unique,
     38     fast_knn_indices,
     39 )
     40 from umap.spectral import spectral_layout

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/umap/sparse.py:12
      9 import numba
     10 import numpy as np
---> 12 from umap.utils import norm
     14 locale.setlocale(locale.LC_NUMERIC, "C")
     16 # Just reproduce a simpler version of numpy unique (not numba supported yet)

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/umap/utils.py:41
     36         knn_indices[row] = v
     37     return knn_indices
     40 @numba.njit("i4(i8[:])")
---> 41 def tau_rand_int(state):
     42     """A fast (pseudo)-random number generator.
     43 
     44     Parameters
   (...)
     51     A (pseudo)-random int32 value
     52     """
     53     state[0] = (((state[0] & 4294967294) << 12) & 0xFFFFFFFF) ^ (
     54         (((state[0] << 13) & 0xFFFFFFFF) ^ state[0]) >> 19
     55     )

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/decorators.py:219, in _jit.<locals>.wrapper(func)
    217     with typeinfer.register_dispatcher(disp):
    218         for sig in sigs:
--> 219             disp.compile(sig)
    220         disp.disable_compile()
    221 return disp

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py:965, in Dispatcher.compile(self, sig)
    963 with ev.trigger_event("numba:compile", data=ev_details):
    964     try:
--> 965         cres = self._compiler.compile(args, return_type)
    966     except errors.ForceLiteralArg as e:
    967         def folded(args, kws):

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py:125, in _FunctionCompiler.compile(self, args, return_type)
    124 def compile(self, args, return_type):
--> 125     status, retval = self._compile_cached(args, return_type)
    126     if status:
    127         return retval

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py:139, in _FunctionCompiler._compile_cached(self, args, return_type)
    136     pass
    138 try:
--> 139     retval = self._compile_core(args, return_type)
    140 except errors.TypingError as e:
    141     self._failed_cache[key] = e

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/dispatcher.py:152, in _FunctionCompiler._compile_core(self, args, return_type)
    149 flags = self._customize_flags(flags)
    151 impl = self._get_implementation(args, {})
--> 152 cres = compiler.compile_extra(self.targetdescr.typing_context,
    153                               self.targetdescr.target_context,
    154                               impl,
    155                               args=args, return_type=return_type,
    156                               flags=flags, locals=self.locals,
    157                               pipeline_class=self.pipeline_class)
    158 # Check typing error if object mode is used
    159 if cres.typing_error is not None and not flags.enable_pyobject:

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py:714, in compile_extra(typingctx, targetctx, func, args, return_type, flags, locals, library, pipeline_class)
    690 def compile_extra(typingctx, targetctx, func, args, return_type, flags,
    691                   locals, library=None, pipeline_class=Compiler):
    692     """Compiler entry point
    693 
    694     Parameter
   (...)
    712         compiler pipeline
    713     """
--> 714     pipeline = pipeline_class(typingctx, targetctx, library,
    715                               args, return_type, flags, locals)
    716     return pipeline.compile_extra(func)

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/compiler.py:408, in CompilerBase.__init__(self, typingctx, targetctx, library, args, return_type, flags, locals)
    404 def __init__(self, typingctx, targetctx, library, args, return_type, flags,
    405              locals):
    406     # Make sure the environment is reloaded
    407     config.reload_config()
--> 408     typingctx.refresh()
    409     targetctx.refresh()
    411     self.state = StateDict()

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/typing/context.py:158, in BaseContext.refresh(self)
    153 def refresh(self):
    154     """
    155     Refresh context with new declarations from known registries.
    156     Useful for third-party extensions.
    157     """
--> 158     self.load_additional_registries()
    159     # Some extensions may have augmented the builtin registry
    160     self._load_builtins()

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/typing/context.py:701, in Context.load_additional_registries(self)
    700 def load_additional_registries(self):
--> 701     from . import (
    702         cffi_utils,
    703         cmathdecl,
    704         enumdecl,
    705         listdecl,
    706         mathdecl,
    707         npydecl,
    708         randomdecl,
    709         setdecl,
    710         dictdecl,
    711     )
    712     self.install_registry(cffi_utils.registry)
    713     self.install_registry(cmathdecl.registry)

File ~/miniconda3/envs/py38/lib/python3.8/site-packages/numba/core/typing/cffi_utils.py:19
     17 try:
     18     import cffi
---> 19     ffi = cffi.FFI()
     20 except ImportError:
     21     ffi = None

AttributeError: module 'cffi' has no attribute 'FFI'

**Comment by AnaAzambuja** [comment]
Solved. I started a new virtual env with conda. 
thanks for your help!
