### ISSUE TITLE
import multivelo KeyError

### ISSUE THREAD

**Issue by mossconfuse** [welch-lab/MultiVelo#2]
I  am new to R, and entirely unfamiliar with python, so this may be a basic issue on my end. 

When I import the necessary packages in R to run the MultiVelo demo, I get the error 
`KeyError: <ufunc 'invert'>` when it gets to `>>> import multivelo as mv`.
The preceding imports were executed successfully.

Thanks for any help.

**Comment by danielee0707** [comment]
Hi. I'm actually not familiar with this error, but let me try to reproduce it. Can you tell me what version of scipy, numpy, scanpy, and scvelo did you use? You can print it with `scipy.__version__`, for example.

**Comment by mossconfuse** [comment]
Thanks for the quick response. Here are the print-outs for `.__version__`:
scipy : '1.7.3'
numpy :'1.22.1'
scanpy : '1.8.2'
scvelo : '0.2.4'

I did have to run the line`pip install numba==0.53` before, because I initially got stuck with the error:
`>>> import scvelo as scv`
`ImportError: Numba needs NumPy 1.21 or less`

**Comment by danielee0707** [comment]
I wasn't able to reproduce the error in python or through Rstudio using the same versions. Are you using Rstudio + reticulate to run the demo? If so, can you let me know which version of R, reticulate, and Rstudio you used? Also, it may be worth trying running it in a native python environment directly.

**Comment by mossconfuse** [comment]
R version : 4.1.1 (2021-08-10)
RStudio version : RStudio 2021.09.1+372 "Ghost Orchid" Release (8b9ced188245155642d024aa3630363df611088a, 2021-11-08) for macOS
Mozilla/5.0 (Macintosh; Intel Mac OS X 11_6_0) AppleWebKit/537.36 (KHTML, like Gecko) QtWebEngine/5.12.10 Chrome/69.0.3497.128 Safari/537.36
![image](https://user-images.githubusercontent.com/95281562/152277710-63efa28a-172e-4197-bacf-d9a5e4a1537f.png)
rstudioapi : 0.13
reticulate version : 1.24
