### ISSUE TITLE
Cannot reproduce Fig4a in the SHARE-seq example

### ISSUE THREAD

**Issue by xixi-cathy** [welch-lab/MultiVelo#34]
Hello,

I tried to reproduce the results in "[MultiVelo_Fig4.ipynb](https://github.com/welch-lab/MultiVelo/blob/main/Examples/MultiVelo_Fig4.ipynb)", but my scatterplot of latent time calculated by multivelo looks like this:
![微信截图_20230922211959](https://github.com/welch-lab/MultiVelo/assets/57483791/97a79a41-234e-412d-a765-5f52a2d14ba7)
It is different from the figure provided, and it seems incorrect for the Medulla lineage. I strictly followed the code in the notebook. I wonder what's going on here?

**Comment by xixi-cathy** [comment]
Ok, I may figure out what the problem is. It seems that the adata_result.obs["root_cells"] and adata_result.obs["end_points"] cannot be overwritten when running 

> mv.latent_time(adata_result)

So things go wrong if I run all the way down, since scvelo first adds "root_cells" and "end_points" to data slots. It's better to clarify that somewhere to avoid confusion. Also, the result file "multivelo_result_fig4.h5ad" provided on figshare should be replaced by the correct one.

**Comment by jacobrepucci** [comment]
Which version of Multivelo, scvelo, and python are you running? I'm able to reproduce the correct graph so I wonder if part of the problem is how different versions interact with each other. In addition it may help to know which OS your machine uses.

**Comment by danielee0707** [comment]
Hi @xixi-cathy, thank you for pointing out the problem! The notebooks on RTD have been updated to fix this issue.
