### ISSUE TITLE
Multivelo recover_dynamics_chrom function question

### ISSUE THREAD

**Issue by AlMuCan** [welch-lab/MultiVelo#6]
Hi, 

I'm trying to run Multivelo on some locally generated 10x data, when running recover_dynamic_chrom I am getting the following exception:

line 942, in check_partial_trajectory
    if (ss_u == 0) or (ss_s == 0):
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

The process looks like it started and crashed part-way through - with verbose set to 2 I got the following
[Parallel(n_jobs=8)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=8)]: Done   3 out of   8 | elapsed:    4.9s remaining:    8.2s
[Parallel(n_jobs=8)]: Done   5 out of   8 | elapsed:    4.9s remaining:    2.9s

Have you all seen this error before? Is there any additional information I could provide to help work out what is happening here?

Thanks in advance for any help you are able to provide

**Comment by AlMuCan** [comment]
Thanks sorry I think I missed that the other issue was actually the same problem. So far so good. It appears to be running.

**Comment by danielee0707** [comment]
Issue closed.
