### ISSUE TITLE
Cannot subset using  adata_rna = adata_rna[cell_annot.index,:]

### ISSUE THREAD

**Issue by JasonOSS** [welch-lab/MultiVelo#7]
Hello, 

I tried to run MultiVelo on the test dataset and had no issues, but when trying on my own data, I am having a KeyError when trying to run:
```
adata_rna = adata_rna[cell_annot.index,:]
adata_rna.obs['clusterID'] = cell_annot['clusterID']
```
(step 7 of your notebook)

Here is the error that I am getting:

KeyError                                  Traceback (most recent call last)
Input In [19], in <cell line: 1>()
----> 1 adata_rna = adata_rna[cell_annot.index,:]
      2 adata_rna.obs['clusterID'] = cell_annot['clusterID']

File ~/.conda/envs/scanpy/lib/python3.8/site-packages/anndata/_core/anndata.py:1113, in AnnData.__getitem__(self, index)
   1111 def __getitem__(self, index: Index) -> "AnnData":
   1112     """Returns a sliced view of the object."""
-> 1113     oidx, vidx = self._normalize_indices(index)
   1114     return AnnData(self, oidx=oidx, vidx=vidx, asview=True)

File ~/.conda/envs/scanpy/lib/python3.8/site-packages/anndata/_core/anndata.py:1094, in AnnData._normalize_indices(self, index)
   1093 def _normalize_indices(self, index: Optional[Index]) -> Tuple[slice, slice]:
-> 1094     return _normalize_indices(index, self.obs_names, self.var_names)

File ~/.conda/envs/scanpy/lib/python3.8/site-packages/anndata/_core/index.py:35, in _normalize_indices(index, names0, names1)
     33         index = index[0].values, index[1]
     34 ax0, ax1 = unpack_index(index)
---> 35 ax0 = _normalize_index(ax0, names0)
     36 ax1 = _normalize_index(ax1, names1)
     37 return ax0, ax1

File ~/.conda/envs/scanpy/lib/python3.8/site-packages/anndata/_core/index.py:101, in _normalize_index(indexer, index)
     99         if np.any(positions < 0):
    100             not_found = indexer[positions < 0]
--> 101             raise KeyError(
    102                 f"Values {list(not_found)}, from {list(indexer)}, "
    103                 "are not valid obs/ var names or indices."
    104             )
    105         return positions  # np.ndarray[int]
    106 else:

KeyError: "Values ['AAACAGCCAGATAGAC-1', 'AAACCAACAACAACAA-1' ........ 'TTTGTTGGTGATCAGC-1', 'TTTGTTGGTTCACCCA-1'], are not valid obs/ var names or indices."

Do you know why I get that error and how can I fix it ?

Thanks in advance for any help you are able to provide

**Comment by danielee0707** [comment]
Hi. This error means that none or not all `cell_annot.index` barcodes are present in the adata_rna object. You can print adata_rna.obs to check if the barcode format matches.

If you're starting with a brand new dataset and following Scanpy's preprocessing [tutorial](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html) to annotate the cell types, you likely won't need the filtering steps in MultiVelo's tutorial. The provided cell_annotations.tsv file is for the test dataset specifically. But if you already have a subset of cell barcodes and corresponding annotations available that you want to extract and run velocity on, which are loaded as `cell_annot,` then you can follow these steps.

**Comment by JasonOSS** [comment]
Hi, I checked that the barcode format match.
I processed the data with Velocyto CLI to get the .loom file that I used in this analysis from cellRancer-arc output.
I processed all my data in Seurat, including the clustering that I want to use here. This clustering only include a part of the data since I filtered out contaminants. Therefore, I have 12107 cells in the Anndata file but 8611 cells in my annotation csv (from Seurat analysis).
Is it this difference that cause the error ?

**Comment by danielee0707** [comment]
That shouldn't be an issue if the 12107 cells include all of the 8611 cells. You can find out how many of them are indeed in the Anndata with 
`np.sum(np.isin(cell_annot.index, adata_rna.obs_names))`
Then `cell_annot_sub = cell_annot[np.isin(cell_annot.index, adata.obs_names)]`

**Comment by JasonOSS** [comment]
Ok, I found where my issue came from.
The filtration:
```
sc.pp.filter_cells(adata_rna, min_counts=1000)
sc.pp.filter_cells(adata_rna, max_counts=20000)
```

is different from the one I used in seurat and indeed caused cells to be present in my cell annotation file but not in the anndata file. 

Thanks a lot for your help!

**Comment by danielee0707** [comment]
You're welcome. I will close this issue now.
